/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs2.h"


void
nfsdir_1(char *host,char path[100])
{
	CLIENT *clnt;
	output  *result_1;
	input  getdir_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, nfsDir, dir_vers, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	strcpy(getdir_1_arg.data,path);
	result_1 = getdir_1(&getdir_1_arg, clnt);
	if (result_1 == (output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("Directory is %s\n",result_1->data);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	nfsdir_1 (host,argv[2]);
exit (0);
}
