/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs2.h"
#include <dirent.h>

output *
getdir_1_svc(input *argp, struct svc_req *rqstp)
{
	struct dirent** namelist;
	static output  ob;

	int n;

	n=scandir(argp->data,&namelist,NULL,alphasort);

	strcpy(ob.data,namelist[n-1]->d_name);
	strcat(ob.data,"\n");
	n--;
	while(n--){
		strcat(ob.data,namelist[n]->d_name);
		strcat(ob.data,"\n");
	}

	return &ob;
}
