/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "addLinkedList.h"


void
add_prog_1(char *host,numbers *num)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

#endif	/* DEBUG */

	result_1 = add_1(num, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("THe result is %d\n",*result_1);

	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	int cnt=argc,i=2;
	numbers *ob=(numbers *)malloc(sizeof(numbers));
	numbers *st = ob;
	ob->x=0;
	while(i<cnt){
		ob->x=atoi(argv[i]);
		printf("ob->x: %d\n",ob->x);
		i++;
		
		if(i<cnt){
			ob->next=(numbers *)malloc(sizeof(numbers));
			ob=ob->next;
		}
	}

	ob->next=NULL;

	numbers *np=st;
	printf("THe numbers are :\n");
	while(np){
		printf("%d ",np->x);
		np=np->next;
	}

	add_prog_1 (host,st);
exit (0);
}
