/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "addLinkedList.h"

bool_t
xdr_numbers (XDR *xdrs, numbers *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (numbers), (xdrproc_t) xdr_numbers))
		 return FALSE;
	return TRUE;
}
