/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NFS_H_RPCGEN
#define _NFS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct fileName {
	char name[100];
};
typedef struct fileName fileName;

struct contentsOut {
	char content[1000];
};
typedef struct contentsOut contentsOut;

#define readContent 0x23451111
#define read_vers 1

#if defined(__STDC__) || defined(__cplusplus)
#define getContent 1
extern  contentsOut * getcontent_1(fileName *, CLIENT *);
extern  contentsOut * getcontent_1_svc(fileName *, struct svc_req *);
extern int readcontent_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getContent 1
extern  contentsOut * getcontent_1();
extern  contentsOut * getcontent_1_svc();
extern int readcontent_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_fileName (XDR *, fileName*);
extern  bool_t xdr_contentsOut (XDR *, contentsOut*);

#else /* K&R C */
extern bool_t xdr_fileName ();
extern bool_t xdr_contentsOut ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NFS_H_RPCGEN */
