/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"

contentsOut *
getcontent_1_svc(fileName *argp, struct svc_req *rqstp)
{
	static contentsOut  result;

	/*
	 * insert server code here
	 */

	printf("Trying to open the file %s\n",argp->name);

	FILE *fp;
	fp=fopen(argp->name, "r");
	if(fp==NULL)
	{
		printf("FIle not present\n");
		return NULL;
	}
	else
	{
		printf("File successfully openend\n");
	 fread(result.content, sizeof(char), 1000, fp);
	}
	return &result;
}
