/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"


void
readcontent_1(char *host,char arr[100])
{
	CLIENT *clnt;
	contentsOut  *result_1;
	fileName  getcontent_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, readContent, read_vers, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	strcpy(getcontent_1_arg.name,arr);
	result_1 = getcontent_1(&getcontent_1_arg, clnt);
	if (result_1 == (contentsOut *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		char arr[1000];
		strcpy(arr,result_1->content);
		printf("file is %s\n",arr);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host fileName\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	readcontent_1 (host,argv[2]);
exit (0);
}
