all:
	g++ -std=c++14 swayambhu.cpp -o swb -lpthread
	g++ -std=c++14 tracer.cpp -o tracer -lpcap
	g++ -std=c++14 client.cpp -o client
	g++ -std=c++14 s1.cpp -o s1
	g++ -std=c++14 s2.cpp -o s2
	g++ -std=c++14 s3.cpp -o s3

use:
	g++ -std=c++14 swayambhu.cpp -o swb -lpthread
	g++ -std=c++14 tracer.cpp -o tracer -lpcap
	
serv:
	g++ -std=c++14 s1.cpp -o s1
	g++ -std=c++14 s2.cpp -o s2
	g++ -std=c++14 s3.cpp -o s3